FROM golang:1.24-alpine as builder

RUN go install github.com/air-verse/air@latest \
	&& apk add --no-cache make

WORKDIR /app

#RUN mkdir -p /app/tmp && chmod 755 /app/tmp

COPY go.mod go.sum ./

COPY . .

RUN go mod download

EXPOSE 8090

CMD ["air", "-c", ".air.toml"]

